<template>
  <div class="shell" :data-theme="theme">
    <aside class="sidebar">
      <div class="brand"><div class="logo">STS</div><div><strong>System Tools</strong><span>Sysadmin Operations Suite</span></div></div>
      <button class="home" @click="active=null">Home</button>
      <section v-for="cat in categories" :key="cat.name" class="nav-section">
        <button class="cat" @click="toggle(cat.name)"><span>{{ cat.name }}</span><span>{{ open[cat.name] ? '−' : '+' }}</span></button>
        <div v-show="open[cat.name]" class="cat-tools">
          <button v-for="t in cat.tools" :key="t[0]" :class="['nav-tool',{selected:active===t[0]}]" @click="active=t[0]">{{ t[1] }}</button>
        </div>
      </section>
    </aside>
    <main class="main">
      <header class="top"><div><h1>{{ activeTool?.name || 'System Tools Suite' }}</h1><p>{{ activeTool?.description || 'Original sysadmin, network, security, DevOps, UniFi, and forensic utilities.' }}</p></div><div class="topbar-actions"><input v-model="query" class="search" placeholder="Search tools, categories, capabilities..." /><div class="suite-iconbar" aria-label="Application links"><a class="suite-icon" href="https://github.com/mdziegiel/system-tools-suite" target="_blank" rel="noreferrer" aria-label="GitHub repository" title="GitHub"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 .5a12 12 0 0 0-3.79 23.39c.6.11.82-.26.82-.58v-2.03c-3.34.73-4.04-1.61-4.04-1.61-.55-1.39-1.34-1.76-1.34-1.76-1.09-.75.08-.73.08-.73 1.2.08 1.84 1.24 1.84 1.24 1.07 1.83 2.81 1.3 3.5.99.11-.78.42-1.3.76-1.6-2.67-.31-5.47-1.34-5.47-5.94 0-1.31.47-2.38 1.24-3.22-.12-.3-.54-1.53.12-3.18 0 0 1.01-.32 3.3 1.23a11.5 11.5 0 0 1 6 0c2.28-1.55 3.29-1.23 3.29-1.23.66 1.65.24 2.88.12 3.18.77.84 1.23 1.91 1.23 3.22 0 4.61-2.8 5.63-5.48 5.93.43.37.81 1.1.81 2.22v3.29c0 .32.22.69.83.57A12 12 0 0 0 12 .5Z" /></svg></a><button class="suite-icon" type="button" @click="aboutOpen=true" aria-label="About" title="About"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9" fill="none" stroke="currentColor" stroke-width="2"/><path d="M12 10v7M12 7h.01" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg></button><button class="suite-icon" type="button" @click="toggleTheme" aria-label="Toggle theme" title="Toggle theme"><svg v-if="theme==='dark'" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg><svg v-else viewBox="0 0 24 24" aria-hidden="true"><path d="M21 14.5A8.5 8.5 0 1 1 9.5 3a7 7 0 0 0 11.5 11.5Z" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg></button></div></div></header>
      <ToolPage v-if="activeTool" :tool="activeTool" @back="active=null" />
      <template v-else>
        <section class="hero"><h2>Professional infrastructure tools. No toy scaffolding.</h2><p>Run server-side diagnostics from the container, do sensitive browser-only operations locally, and keep forensic cases in persistent SQLite storage.</p></section>
        <ToolGrid title="Newest Tools" :items="newest" @open="active=$event" />
        <ToolGrid title="Favorites" :items="favoriteTools" empty="Pinned tools appear here. Click the heart on any card." @open="active=$event" />
        <ToolGrid title="All Tools" :items="filtered" @open="active=$event" />
      </template>
    </main>
    <div v-if="aboutOpen" class="suite-modal-backdrop" role="dialog" aria-modal="true" aria-label="About System Tools Suite" @click="aboutOpen=false"><div class="suite-modal" @click.stop><button class="suite-modal-close" type="button" @click="aboutOpen=false" aria-label="Close">×</button><div class="suite-modal-kicker">About</div><h2>System Tools Suite</h2><p class="suite-modal-version">Version 2.0.0</p><p>Original sysadmin, network, system, security, DevOps, UniFi, and forensic tools suite for MRDTech.</p></div></div>
  </div>
</template>

<script setup>
import { computed, reactive, ref, onMounted } from 'vue'
import yaml from 'js-yaml'
import * as TOML from '@ltd/j-toml'
import cronstrue from 'cronstrue'
import CryptoJS from 'crypto-js'
import { categories, tools } from './tools.js'
const active = ref(null), query = ref('')
const theme = ref(localStorage.getItem('suite-theme') || 'dark'), aboutOpen = ref(false)
function toggleTheme(){ theme.value = theme.value === 'dark' ? 'light' : 'dark'; localStorage.setItem('suite-theme', theme.value) }
const open = reactive(Object.fromEntries(categories.map(c=>[c.name,true])))
const favorites = ref(JSON.parse(localStorage.getItem('sts:favorites') || '[]'))
function toggle(name){ open[name]=!open[name] }
function fav(slug){ favorites.value = favorites.value.includes(slug) ? favorites.value.filter(x=>x!==slug) : [...favorites.value, slug]; localStorage.setItem('sts:favorites', JSON.stringify(favorites.value)) }
const activeTool = computed(()=>tools.find(t=>t.slug===active.value))
const newest = computed(()=>tools.filter(t=>t.badge==='new'))
const favoriteTools = computed(()=>tools.filter(t=>favorites.value.includes(t.slug)))
const filtered = computed(()=>tools.filter(t=>(t.name+t.description+t.category).toLowerCase().includes(query.value.toLowerCase())))

const eventMap={4624:['Security','Informational','Successful logon','Confirm account, logon type, source workstation/IP.'],4625:['Security','Warning','Failed logon','Bad password, disabled account, brute force, stale service credential.'],4634:['Security','Informational','Logoff','Normal session termination.'],4648:['Security','Warning','Explicit credential logon','Review run-as usage and lateral movement indicators.'],4720:['Security','High','User account created','Validate ticket/change owner and privileged group membership.'],4728:['Security','High','Member added to global security group','Audit privilege escalation.'],4732:['Security','High','Member added to local security group','Review local admin expansion.'],4740:['Security','Warning','Account locked out','Find caller computer and bad password source.'],4768:['Security','Informational','Kerberos TGT requested','Baseline domain auth volume.'],4769:['Security','Informational','Kerberos service ticket requested','Review unusual SPN access.'],4771:['Security','Warning','Kerberos pre-auth failed','Password spray or time skew.'],7045:['System','High','Service installed','Investigate persistence or legitimate software deployment.'],7036:['System','Informational','Service state changed','Correlate with maintenance or crash.']}
const syslog=['Emergency: system unusable','Alert: immediate action required','Critical: critical condition','Error: error condition','Warning: warning condition','Notice: normal but significant','Informational: informational message','Debug: debug-level message']

function defaultInput(slug){ return ({
 'ping-traceroute':{target:'1.1.1.1',mode:'ping'}, 'port-scanner':{host:'scanme.nmap.org',start_port:22,end_port:85}, 'dns-lookup':{domain:'example.com',record_type:'A'}, 'reverse-dns':{ip:'8.8.8.8'}, whois:{domain:'example.com'}, 'ssl-checker':{host:'example.com',port:443}, 'bgp-asn':{asn:'AS15169'}, 'ip-geolocation':{ip:'8.8.8.8'}, 'wake-on-lan':{mac:'00:11:22:33:44:55',broadcast:'255.255.255.255',port:9}, 'http-headers':{url:'https://example.com'}, 'response-time':{url:'https://example.com'}, 'nat-translator':{private_cidr:'192.168.1.0/24',public_cidr:'203.0.113.0/24',address:'192.168.1.50'}, 'rbl-checker':{ip:'8.8.8.8'}, 'smart-checker':{device:'/dev/sda',sample:''}, 'cve-lookup':{query:'CVE-2024-3094'}, virustotal:{indicator:'8.8.8.8'}, 'ioc-scanner':{items:'8.8.8.8\nexample.com'}, 'unifi-client':{controller_url:'https://10.10.10.1',api_key:'',query:'00:11:22:33:44:55'}, 'subnet-calculator':{cidr:'192.168.10.0/24'}, 'bandwidth-calculator':{size:10,size_unit:'GB',bandwidth:100,bandwidth_unit:'Mbps'}, 'password-generator':{length:20,count:5,upper:true,lower:true,numbers:true,symbols:true,ambiguous:false}, 'password-strength':{password:'CorrectHorseBatteryStaple!2026'}, 'ssh-key-generator':{type:'RSA-2048'}, 'hash-tool':{text:'MRDTech',algorithm:'SHA-256',verify:''}, 'jwt-decoder':{jwt:''}, base64:{mode:'encode',text:'MRDTech'}, 'cidr-rule-builder':{cidr:'10.10.10.0/24',action:'allow',port:'443',protocol:'tcp'}, 'docker-compose-converter':{command:'docker run -d --name web -p 8080:80 -e TZ=UTC nginx:latest'}, 'k8s-calculator':{replicas:3,cpu_request:250,cpu_limit:500,mem_request:256,mem_limit:512}, 'terraform-formatter':{vars:'region=string=us-east-1\ninstance_count=number=2'}, 'data-converter':{from:'json',to:'yaml',text:'{"name":"mrdtech","secure":true}'}, 'unifi-vlan':{name:'Servers',vlan_id:30,subnet:'10.10.30.0/24',gateway:'10.10.30.1'}, 'unifi-port-profile':{name:'AP Trunk',native_vlan:10,tagged_vlans:'20,30,40',voice_vlan:50}, 'cron-builder':{minute:'0',hour:'2',dom:'*',month:'*',dow:'*'}, 'uptime-calculator':{period_hours:720,downtime_minutes:43}, 'event-id':{id:4625}, 'syslog-severity':{level:4}, 'ldap-dn':{cn:'Michael Dziegiel',ous:'Users,MRDTech',dcs:'mrdtech,local'}, 'gpo-path':{domain:'mrdtech.local',guid:'{31B2F340-016D-11D2-945F-00C04FB984F9}'}, 'vlan-calculator':{vlan_id:30,mode:'trunk'}, 'cert-decoder':{pem:''}, 'file-hash':{}, 'metadata-extractor':{}, 'string-finder':{}, 'log-analyzer':{}, 'case-manager':{case_action:'create',case_id:'',case_title:'Incident Review',case_description:'Initial case notes',note_body:'',evidence_name:'',evidence_kind:'disk image',evidence_sha256:'',timeline_event:'',occurred_at:''}
 })[slug] || {} }
function fieldsFor(slug){ const f={
 'ping-traceroute':[['target','Target hostname or IP'],['mode','Mode: ping or traceroute']], 'port-scanner':[['host','Host'],['start_port','Start port'],['end_port','End port']], 'dns-lookup':[['domain','Domain'],['record_type','Record type']], 'reverse-dns':[['ip','IP address']], whois:[['domain','Domain']], 'ssl-checker':[['host','Hostname'],['port','Port']], 'bgp-asn':[['asn','ASN like AS15169']], 'ip-geolocation':[['ip','IP address']], 'wake-on-lan':[['mac','MAC address'],['broadcast','Broadcast address'],['port','UDP port']], 'http-headers':[['url','URL']], 'response-time':[['url','URL']], 'nat-translator':[['private_cidr','Private CIDR'],['public_cidr','Public CIDR'],['address','Private address']], 'rbl-checker':[['ip','IP address']], 'smart-checker':[['device','Device path'],['sample','Paste smartctl output instead of querying device']], 'cve-lookup':[['query','CVE ID or keyword']], virustotal:[['indicator','URL, IP, domain, or hash']], 'ioc-scanner':[['items','One IOC per line']], 'unifi-client':[['controller_url','Controller URL'],['api_key','API key'],['query','MAC or IP']], 'case-manager':[['case_action','Action: create, list, add_note, add_evidence, add_timeline, export, delete'],['case_id','Case ID for existing case'],['case_title','Case title'],['case_description','Description'],['note_body','Note body'],['evidence_name','Evidence name'],['evidence_kind','Evidence kind'],['evidence_sha256','Evidence SHA256'],['timeline_event','Timeline event'],['occurred_at','Occurred at ISO timestamp']]
 }; return f[slug] || Object.keys(defaultInput(slug)).map(k=>[k,k.replaceAll('_',' ')]) }
function ipToNum(ip){return ip.split('.').reduce((a,o)=>((a<<8)+Number(o))>>>0,0)}
function numToIp(n){return [24,16,8,0].map(s=>(n>>>s)&255).join('.')}
function subnet(cidr){let [ip,p]=cidr.split('/');p=Number(p);let mask=(0xffffffff<<(32-p))>>>0, net=ipToNum(ip)&mask, bc=(net|(~mask>>>0))>>>0, hosts=Math.max(0,2**(32-p)-2);return {cidr,network:numToIp(net),broadcast:numToIp(bc),netmask:numToIp(mask),wildcard:numToIp((~mask)>>>0),first_usable:hosts?numToIp(net+1):null,last_usable:hosts?numToIp(bc-1):null,usable_hosts:hosts}}
function pem(label, buf){const b64=btoa(String.fromCharCode(...new Uint8Array(buf))).match(/.{1,64}/g).join('\n');return `-----BEGIN ${label}-----\n${b64}\n-----END ${label}-----`}
async function generateKeyPair(type){
 const bits=type.includes('4096')?4096:2048
 const key=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:bits,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify'])
 const pub=await crypto.subtle.exportKey('spki',key.publicKey); const priv=await crypto.subtle.exportKey('pkcs8',key.privateKey)
 return {type:`RSA-${bits}`,public_key_pem:pem('PUBLIC KEY',pub),private_key_pem:pem('PRIVATE KEY',priv),note:'Generated locally in browser WebCrypto. Convert to OpenSSH format before production SSH deployment.'}
}
function allHashes(text){return {md5:CryptoJS.MD5(text).toString(),sha1:CryptoJS.SHA1(text).toString(),sha256:CryptoJS.SHA256(text).toString(),sha512:CryptoJS.SHA512(text).toString()}}
function frontendRun(slug,input){
 if(slug==='subnet-calculator')return subnet(input.cidr)
 if(slug==='vlan-calculator')return {vlan_id:input.vlan_id, range:Number(input.vlan_id)<=1005?'normal range':'extended range', reserved:'0, 1, 1002-1005, 4095', mode:input.mode, access:'Access ports carry one untagged VLAN.', trunk:'Trunks carry tagged VLANs using 802.1Q.', native:'Native VLAN is untagged on a trunk; do not use VLAN 1 in sane environments.'}
 if(slug==='bandwidth-calculator'){let bytes=input.size*({KB:1e3,MB:1e6,GB:1e9,TB:1e12}[input.size_unit]||1);let bps=input.bandwidth*({Kbps:1e3,Mbps:1e6,Gbps:1e9}[input.bandwidth_unit]||1);let sec=bytes*8/bps;return {seconds:sec, human:`${Math.floor(sec/3600)}h ${Math.floor(sec%3600/60)}m ${Math.round(sec%60)}s`}}
 if(slug==='password-generator'){let sets=[input.upper&&'ABCDEFGHJKLMNPQRSTUVWXYZ',input.lower&&'abcdefghijkmnopqrstuvwxyz',input.numbers&&'23456789',input.symbols&&'!@#$%^&*_-+=?'].filter(Boolean).join(''); if(input.ambiguous)sets+='0OolI1'; return Array.from({length:input.count},()=>Array.from(crypto.getRandomValues(new Uint32Array(input.length))).map(n=>sets[n%sets.length]).join(''))}
 if(slug==='password-strength'){let classes=[/[a-z]/,/[A-Z]/,/\d/,/[^A-Za-z0-9]/].filter(r=>r.test(input.password)).length;let pool=[26,26,10,32].slice(0,classes).reduce((a,b)=>a+b,0)||1;let entropy=Math.round(input.password.length*Math.log2(pool));return {entropy_bits:entropy, score:entropy>100?'excellent':entropy>70?'strong':entropy>45?'fair':'weak', weaknesses:[input.password.length<14?'too short':null,/(password|admin|welcome|qwerty)/i.test(input.password)?'common word':null,/(.)\1{2,}/.test(input.password)?'repeated chars':null].filter(Boolean), offline_crack_estimate: entropy>80?'centuries at commodity speeds':'assume crackable if dumped into a real cracking rig'}}
 if(slug==='ssh-key-generator')return generateKeyPair(input.type)
 if(slug==='hash-tool'){let h=allHashes(input.text);return {...h, verified:input.verify? Object.values(h).includes(input.verify.toLowerCase()):null}}
 if(slug==='jwt-decoder'){let [h,p]=input.jwt.split('.'); return {header:JSON.parse(atob((h||'').replace(/-/g,'+').replace(/_/g,'/'))||'{}'), payload:JSON.parse(atob((p||'').replace(/-/g,'+').replace(/_/g,'/'))||'{}'), verified:false, note:'Decoded only. Signature is not verified.'}}
 if(slug==='base64')return input.mode==='decode'?atob(input.text):btoa(input.text)
 if(slug==='cidr-rule-builder')return {iptables:`iptables -A INPUT -p ${input.protocol} -s ${input.cidr} --dport ${input.port} -j ${input.action==='allow'?'ACCEPT':'DROP'}`,ufw:`ufw ${input.action} from ${input.cidr} to any port ${input.port} proto ${input.protocol}`,windows:`New-NetFirewallRule -DisplayName "STS ${input.action} ${input.cidr}" -Direction Inbound -RemoteAddress ${input.cidr} -Protocol ${input.protocol.toUpperCase()} -LocalPort ${input.port} -Action ${input.action==='allow'?'Allow':'Block'}`,pfsense:{type:'pass/block',source:input.cidr,destination_port:input.port,protocol:input.protocol}}
 if(slug==='docker-compose-converter'){let parts=input.command.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g)||[];let image=parts.at(-1);let ports=[],env=[],name='converted';parts.forEach((p,i)=>{if(p==='--name')name=parts[i+1]; if(p==='-p'||p==='--publish')ports.push(parts[i+1]); if(p==='-e'||p==='--env')env.push(parts[i+1])});return `services:\n  ${name}:\n    image: ${image}\n    restart: unless-stopped\n    ports:\n${ports.map(p=>'      - "'+p+'"').join('\n')}\n    environment:\n${env.map(e=>'      - '+e).join('\n')}`}
 if(slug==='k8s-calculator')return {replicas:input.replicas,total_cpu_request_millicores:input.replicas*input.cpu_request,total_cpu_limit_millicores:input.replicas*input.cpu_limit,total_memory_request_mib:input.replicas*input.mem_request,total_memory_limit_mib:input.replicas*input.mem_limit}
 if(slug==='terraform-formatter')return input.vars.split('\n').filter(Boolean).map(l=>{let [n,t,d]=l.split('=');return `variable "${n}" {\n  type = ${t||'string'}\n  default = ${JSON.stringify(d||'')}\n}`}).join('\n\n')
 if(slug==='data-converter'){let obj=input.from==='json'?JSON.parse(input.text):input.from==='yaml'?yaml.load(input.text):TOML.parse(input.text); return input.to==='json'?JSON.stringify(obj,null,2):input.to==='yaml'?yaml.dump(obj):TOML.stringify(obj)}
 if(slug==='unifi-vlan')return {name:input.name,purpose:'corporate',vlan_enabled:true,vlan:input.vlan_id,subnet:input.subnet,gateway:input.gateway,dhcp_enabled:true}
 if(slug==='unifi-port-profile')return {name:input.name,native_networkconf_id:input.native_vlan,tagged_vlan_mgmt:'custom',tagged_vlans:String(input.tagged_vlans).split(',').map(x=>Number(x.trim())),voice_networkconf_id:Number(input.voice_vlan)||null,poe_mode:'auto'}
 if(slug==='cron-builder'){let expr=`${input.minute} ${input.hour} ${input.dom} ${input.month} ${input.dow}`;return {expression:expr,summary:cronstrue.toString(expr),next_runs:'Calculated by scheduler at runtime; expression is ready for croniter/server validation.'}}
 if(slug==='uptime-calculator'){let mins=input.period_hours*60;let up=100*((mins-input.downtime_minutes)/mins);return {uptime_percent:up.toFixed(5),downtime_minutes:Number(input.downtime_minutes),period_hours:Number(input.period_hours)}}
 if(slug==='event-id'){let e=eventMap[input.id]||['Unknown','Unknown','No built-in mapping','Check Microsoft docs, source log, and environment baseline.'];return {event_id:input.id,source:e[0],severity:e[1],description:e[2],common_cause:e[3]}}
 if(slug==='syslog-severity')return {level:input.level,meaning:syslog[Number(input.level)]||'Invalid severity'}
 if(slug==='ldap-dn'){let ous=String(input.ous).split(',').filter(Boolean).map(x=>'OU='+x.trim()).join(',');let dcs=String(input.dcs).split(',').filter(Boolean).map(x=>'DC='+x.trim()).join(',');return `CN=${input.cn},${ous},${dcs}`}
 if(slug==='gpo-path')return `\\${input.domain}\\SYSVOL\\${input.domain}\\Policies\\${input.guid}`
 if(slug==='cert-decoder')return {note:'Paste PEM and use openssl for authoritative parsing. Browser-only decoder avoids sending cert text; PEM length shown for quick sanity.', pem_length:(input.pem||'').length, has_certificate:(input.pem||'').includes('BEGIN CERTIFICATE')}
 return input
}

const ToolGrid={props:['title','items','empty'],emits:['open'],template:`<section class="grid-section"><h2>{{title}}</h2><p v-if="!items.length" class="empty">{{empty||'No tools match.'}}</p><div class="grid"><article v-for="t in items" :key="t.slug" class="card" @click="$emit('open',t.slug)"><div class="card-head"><span class="badge">{{t.category.replace(' Tools','')}}</span><button @click.stop="fav(t.slug)" class="heart">{{favorites.includes(t.slug)?'♥':'♡'}}</button></div><h3>{{t.name}}</h3><p>{{t.description}}</p><small v-if="t.badge==='new'">Newest</small></article></div></section>`,setup(){return{favorites,fav}}}
const ToolPage={props:['tool'],emits:['back'],setup(props){const input=ref(defaultInput(props.tool.slug));const output=ref(null),loading=ref(false),error=ref('');const file=ref(null);async function run(){loading.value=true;error.value='';output.value=null;try{if(['file-hash','metadata-extractor','string-finder','log-analyzer'].includes(props.tool.slug)){let fd=new FormData();fd.append('file',file.value);let r=await fetch(`/api/tools/${props.tool.slug}/upload`,{method:'POST',body:fd});output.value=await r.json();if(!r.ok)throw new Error(output.value.detail||'upload failed')}else if(props.tool.mode==='backend'){let r=await fetch(`/api/tools/${props.tool.slug}/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input.value)});output.value=await r.json();if(!r.ok)throw new Error(output.value.detail||'request failed')}else{output.value=await frontendRun(props.tool.slug,input.value)}}catch(e){error.value=e.message}finally{loading.value=false}}onMounted(()=>{if(props.tool.mode==='frontend'&&!['ssh-key-generator','jwt-decoder','cert-decoder'].includes(props.tool.slug))run()});return{input,output,loading,error,fieldsFor,run,file,favorites,fav}},template:`<section class="tool-page"><button class="back" @click="$emit('back')">← Back to tools</button><div class="tool-title"><div><h2>{{tool.name}}</h2><p>{{tool.description}} Configure the fields below, run the tool, and review structured output. Browser-only tools do not send sensitive content to the server.</p></div><button class="heart big" @click="fav(tool.slug)">{{favorites.includes(tool.slug)?'♥':'♡'}}</button></div><div class="runner"><div class="form"><template v-if="['file-hash','metadata-extractor','string-finder','log-analyzer'].includes(tool.slug)"><label>Upload file<input type="file" @change="file=$event.target.files[0]"></label></template><template v-else><label v-for="[key,label] in fieldsFor(tool.slug)" :key="key">{{label}}<textarea v-if="String(input[key]||'').includes('\n') || key==='sample' || key==='pem' || key==='text' || key==='items' || key==='command' || key==='vars'" v-model="input[key]"></textarea><input v-else-if="typeof input[key]==='boolean'" type="checkbox" v-model="input[key]"><input v-else v-model="input[key]"></label></template><button class="run" @click="run" :disabled="loading">{{loading?'Running...':'Run Tool'}}</button><p class="error" v-if="error">{{error}}</p></div><pre class="output">{{ output==null ? 'Output will appear here.' : (typeof output==='string'?output:JSON.stringify(output,null,2)) }}</pre></div></section>`}
</script>
