import type { Component } from 'vue';
import { Alarm, AlignJustified, Braces, BrandDocker, Calendar, Certificate, Code, Database, Devices, EyeOff, FileDiff, FileText, Fingerprint, Key, Lock, LockSquare, Server, World } from '@vicons/tabler';
import { defineTool } from '../tool';

export type FieldType = 'text' | 'textarea' | 'number' | 'select' | 'file';
export interface SuiteField { key: string; label: string; type?: FieldType; placeholder?: string; default?: string | number; options?: string[] }
export interface SuiteToolDef { slug: string; name: string; category: 'Network Tools' | 'System Tools' | 'Security Tools' | 'DevOps Tools' | 'Forensic Tools'; description: string; mode: 'api' | 'local' | 'file' | 'case'; apiTool?: string; fields: SuiteField[]; icon: Component; keywords: string[] }

export const suiteTools: SuiteToolDef[] = [
  { slug: 'ping-traceroute', name: 'Ping / Traceroute', category: 'Network Tools', description: 'Run ping or traceroute from the server against a host.', mode: 'api', apiTool: 'ping', icon: Devices, keywords: ['ping','traceroute','network'], fields: [{key:'mode',label:'Mode',type:'select',default:'ping',options:['ping','traceroute']},{key:'target',label:'Target',placeholder:'example.com or 10.10.10.1'},{key:'count',label:'Ping count',type:'number',default:4},{key:'max_hops',label:'Traceroute max hops',type:'number',default:20}]},
  { slug: 'port-scanner', name: 'Port Scanner', category: 'Network Tools', description: 'Scan a host for open TCP ports with a bounded range.', mode: 'api', apiTool: 'port-scan', icon: Server, keywords: ['port','scan','tcp'], fields: [{key:'host',label:'Host',placeholder:'10.10.10.237'},{key:'ports',label:'Ports',default:'1-1024',placeholder:'22,80,443 or 1-1024'},{key:'timeout',label:'Timeout seconds',type:'number',default:0.4}]},
  { slug: 'dns-lookup', name: 'DNS Lookup', category: 'Network Tools', description: 'Resolve A, AAAA, MX, TXT, PTR, CNAME, and NS records.', mode: 'api', apiTool: 'dns-lookup', icon: World, keywords: ['dns','a','mx','txt','ptr','cname','ns'], fields: [{key:'target',label:'Name or IP'},{key:'rtype',label:'Record type',type:'select',default:'A',options:['A','AAAA','MX','TXT','PTR','CNAME','NS']}]},
  { slug: 'whois-lookup', name: 'WHOIS Lookup', category: 'Network Tools', description: 'Fetch domain registration and registry information.', mode: 'api', apiTool: 'whois-lookup', icon: FileText, keywords: ['whois','domain'], fields: [{key:'domain',label:'Domain',placeholder:'example.com'}]},
  { slug: 'ssl-certificate-checker', name: 'SSL Certificate Checker', category: 'Network Tools', description: 'Check certificate validity, expiry, issuer, SANs, and fingerprint.', mode: 'api', apiTool: 'ssl-checker', icon: Certificate, keywords: ['ssl','tls','certificate'], fields: [{key:'host',label:'Hostname',placeholder:'example.com'},{key:'port',label:'Port',type:'number',default:443}]},
  { slug: 'subnet-calculator-plus', name: 'Subnet Calculator Plus', category: 'Network Tools', description: 'CIDR network, broadcast, netmask, wildcard, and usable hosts.', mode: 'local', icon: Devices, keywords: ['subnet','cidr','network'], fields: [{key:'cidr',label:'CIDR',default:'192.168.1.0/24'}]},
  { slug: 'vlan-calculator', name: 'VLAN Calculator', category: 'Network Tools', description: 'Validate VLAN IDs and summarize access/trunk/native VLAN use.', mode: 'local', icon: Devices, keywords: ['vlan','trunk','switch'], fields: [{key:'vlanId',label:'VLAN ID',type:'number',default:10},{key:'nativeVlan',label:'Native VLAN',type:'number',default:1},{key:'allowedVlans',label:'Allowed VLANs',default:'10,20,30-40'}]},
  { slug: 'bgp-asn-lookup', name: 'BGP ASN Lookup', category: 'Network Tools', description: 'Resolve ASN owner, country, and public prefixes.', mode: 'api', apiTool: 'bgp-asn-lookup', icon: World, keywords: ['bgp','asn','prefix'], fields: [{key:'query',label:'ASN',placeholder:'15169'}]},
  { slug: 'bandwidth-calculator', name: 'Network Bandwidth Calculator', category: 'Network Tools', description: 'Estimate transfer time or throughput from size and bandwidth.', mode: 'local', icon: Devices, keywords: ['bandwidth','throughput'], fields: [{key:'sizeGb',label:'Data size GB',type:'number',default:100},{key:'mbps',label:'Bandwidth Mbps',type:'number',default:1000},{key:'overhead',label:'Protocol overhead %',type:'number',default:5}]},

  { slug: 'smart-health-checker', name: 'SMART Disk Health Checker', category: 'System Tools', description: 'Parse smartctl output or query a device when container privileges allow it.', mode: 'api', apiTool: 'smart-health', icon: Database, keywords: ['smart','disk','health'], fields: [{key:'device',label:'Device path (optional)',placeholder:'/dev/sda'},{key:'smartctl_output',label:'smartctl -a output',type:'textarea'}]},
  { slug: 'windows-event-id-lookup', name: 'Windows Event ID Lookup', category: 'System Tools', description: 'Offline lookup for common Windows Event IDs with source and severity.', mode: 'local', icon: FileText, keywords: ['windows','event','eventid'], fields: [{key:'eventId',label:'Event ID',default:'4625'}]},
  { slug: 'syslog-severity-calculator', name: 'Syslog Severity Calculator', category: 'System Tools', description: 'Map syslog severity numbers to names and descriptions.', mode: 'local', icon: FileText, keywords: ['syslog','severity'], fields: [{key:'severity',label:'Severity 0-7',type:'number',default:3}]},
  { slug: 'ldap-dn-builder', name: 'AD/LDAP Distinguished Name Builder', category: 'System Tools', description: 'Build LDAP DNs from CN/OU/DC components.', mode: 'local', icon: Database, keywords: ['ldap','active directory','dn'], fields: [{key:'cn',label:'CN',default:'John Smith'},{key:'ous',label:'OUs, top-down comma separated',default:'Users,Corporate'},{key:'domain',label:'DNS domain',default:'corp.example.com'}]},
  { slug: 'gpo-path-calculator', name: 'GPO Path Calculator', category: 'System Tools', description: 'Generate a SYSVOL policy path from domain and GPO GUID or name.', mode: 'local', icon: FileText, keywords: ['gpo','sysvol','active directory'], fields: [{key:'domain',label:'AD domain',default:'corp.example.com'},{key:'gpo',label:'GPO GUID or name',default:'Default Domain Policy'}]},
  { slug: 'cron-builder-plus', name: 'Cron Expression Builder Plus', category: 'System Tools', description: 'Build common cron expressions with a plain-English summary.', mode: 'local', icon: Alarm, keywords: ['cron','schedule'], fields: [{key:'preset',label:'Preset',type:'select',default:'daily',options:['every-minute','hourly','daily','weekly','monthly','custom']},{key:'minute',label:'Minute',default:'0'},{key:'hour',label:'Hour',default:'2'},{key:'day',label:'Day of month',default:'*'},{key:'month',label:'Month',default:'*'},{key:'weekday',label:'Weekday',default:'*'}]},
  { slug: 'uptime-calculator', name: 'Service Uptime Calculator', category: 'System Tools', description: 'Calculate SLA uptime percentage from downtime inputs.', mode: 'local', icon: Calendar, keywords: ['uptime','sla'], fields: [{key:'periodHours',label:'Period hours',type:'number',default:720},{key:'downtimeMinutes',label:'Downtime minutes',type:'number',default:30}]},

  { slug: 'password-generator-plus', name: 'Password Generator Plus', category: 'Security Tools', description: 'Generate passwords with complexity rules and optional ambiguity removal.', mode: 'local', icon: Lock, keywords: ['password','generator'], fields: [{key:'length',label:'Length',type:'number',default:24},{key:'upper',label:'Uppercase count minimum',type:'number',default:2},{key:'lower',label:'Lowercase count minimum',type:'number',default:2},{key:'digits',label:'Digits count minimum',type:'number',default:2},{key:'symbols',label:'Symbols count minimum',type:'number',default:2},{key:'excludeAmbiguous',label:'Exclude ambiguous? yes/no',default:'yes'}]},
  { slug: 'certificate-decoder-plus', name: 'Certificate Decoder Plus', category: 'Security Tools', description: 'Decode PEM certificate fields with OpenSSL.', mode: 'api', apiTool: 'certificate-decoder', icon: Certificate, keywords: ['certificate','pem','x509'], fields: [{key:'pem',label:'PEM certificate',type:'textarea'}]},
  { slug: 'jwt-decoder-plus', name: 'JWT Decoder Plus', category: 'Security Tools', description: 'Decode JWT header and payload without sending it anywhere.', mode: 'local', icon: Key, keywords: ['jwt','decode'], fields: [{key:'jwt',label:'JWT',type:'textarea'}]},
  { slug: 'ssh-key-generator', name: 'SSH Key Generator', category: 'Security Tools', description: 'Generate RSA key material in the browser for lab use.', mode: 'local', icon: Key, keywords: ['ssh','rsa','ed25519','key'], fields: [{key:'algorithm',label:'Algorithm',type:'select',default:'RSA-2048',options:['RSA-2048','RSA-4096']}]},
  { slug: 'hash-generator-verifier', name: 'Hash Generator and Verifier', category: 'Security Tools', description: 'Generate MD5, SHA1, SHA256, and SHA512 hashes and compare expected values.', mode: 'local', icon: EyeOff, keywords: ['hash','sha','md5'], fields: [{key:'text',label:'Text',type:'textarea'},{key:'expected',label:'Expected hash (optional)'}]},
  { slug: 'firewall-rule-builder', name: 'CIDR Firewall Rule Builder', category: 'Security Tools', description: 'Generate allow/deny rules for iptables, UFW, pfSense, and Cisco ACLs.', mode: 'local', icon: LockSquare, keywords: ['firewall','cidr','rule'], fields: [{key:'action',label:'Action',type:'select',default:'allow',options:['allow','deny']},{key:'cidr',label:'CIDR',default:'10.10.10.0/24'},{key:'port',label:'Port/service',default:'443'},{key:'protocol',label:'Protocol',type:'select',default:'tcp',options:['tcp','udp','any']}]},
  { slug: 'cve-lookup', name: 'CVE Lookup', category: 'Security Tools', description: 'Search NVD by CVE ID or keyword.', mode: 'api', apiTool: 'cve-lookup', icon: LockSquare, keywords: ['cve','vulnerability'], fields: [{key:'query',label:'CVE ID or keyword',placeholder:'CVE-2024-3094'}]},

  { slug: 'docker-run-compose-plus', name: 'Docker Run to Compose Plus', category: 'DevOps Tools', description: 'Convert docker run commands to Compose YAML.', mode: 'local', icon: BrandDocker, keywords: ['docker','compose'], fields: [{key:'dockerRun',label:'docker run command',type:'textarea',default:'docker run -d --name web -p 8080:80 nginx'}]},
  { slug: 'kubernetes-resource-calculator', name: 'Kubernetes Resource Calculator', category: 'DevOps Tools', description: 'Calculate aggregate CPU/memory requests and limits.', mode: 'local', icon: Server, keywords: ['kubernetes','resources'], fields: [{key:'replicas',label:'Replicas',type:'number',default:3},{key:'cpuRequest',label:'CPU request millicores',type:'number',default:250},{key:'cpuLimit',label:'CPU limit millicores',type:'number',default:500},{key:'memRequest',label:'Memory request MiB',type:'number',default:256},{key:'memLimit',label:'Memory limit MiB',type:'number',default:512}]},
  { slug: 'terraform-variable-formatter', name: 'Terraform Variable Formatter', category: 'DevOps Tools', description: 'Generate HCL variable blocks.', mode: 'local', icon: Code, keywords: ['terraform','hcl'], fields: [{key:'name',label:'Variable name',default:'instance_count'},{key:'type',label:'Type',default:'number'},{key:'description',label:'Description',default:'Number of instances'},{key:'default',label:'Default value',default:'2'}]},
  { slug: 'data-format-converter-plus', name: 'YAML / JSON / TOML Converter Plus', category: 'DevOps Tools', description: 'Convert between JSON, YAML, and TOML where browser libraries allow.', mode: 'local', icon: Braces, keywords: ['yaml','json','toml'], fields: [{key:'from',label:'From',type:'select',default:'json',options:['json','yaml','toml']},{key:'to',label:'To',type:'select',default:'yaml',options:['json','yaml','toml']},{key:'input',label:'Input',type:'textarea',default:'{"service":"api","replicas":2}'}]},
  { slug: 'cicd-template-generator', name: 'CI/CD Pipeline Template Generator', category: 'DevOps Tools', description: 'Generate GitHub Actions or GitLab CI starter pipelines.', mode: 'local', icon: FileDiff, keywords: ['ci','cd','github actions','gitlab'], fields: [{key:'platform',label:'Platform',type:'select',default:'github',options:['github','gitlab']},{key:'language',label:'Language',type:'select',default:'node',options:['node','python','docker']},{key:'deploy',label:'Include Docker build? yes/no',default:'yes'}]},

  { slug: 'file-hash-verifier', name: 'File Hash Verifier', category: 'Forensic Tools', description: 'Upload a file and calculate MD5, SHA256, and SHA512.', mode: 'file', apiTool: 'hash', icon: Fingerprint, keywords: ['file','hash','forensics'], fields: [{key:'file',label:'File',type:'file'}]},
  { slug: 'metadata-extractor', name: 'Metadata Extractor', category: 'Forensic Tools', description: 'Extract metadata from PDF, Office, and image files.', mode: 'file', apiTool: 'metadata', icon: FileText, keywords: ['metadata','exif'], fields: [{key:'file',label:'File',type:'file'}]},
  { slug: 'string-finder', name: 'String Finder', category: 'Forensic Tools', description: 'Extract readable strings from a binary file.', mode: 'file', apiTool: 'strings', icon: AlignJustified, keywords: ['strings','binary'], fields: [{key:'file',label:'File',type:'file'}]},
  { slug: 'log-analyzer', name: 'Log Analyzer', category: 'Forensic Tools', description: 'Upload syslog-style text and flag suspicious lines.', mode: 'file', apiTool: 'log', icon: FileText, keywords: ['log','syslog','evtx'], fields: [{key:'file',label:'Log file',type:'file'}]},
  { slug: 'ioc-scanner', name: 'IOC Scanner', category: 'Forensic Tools', description: 'Classify indicators and check AbuseIPDB/VirusTotal when API keys are configured.', mode: 'api', apiTool: 'ioc-scanner', icon: LockSquare, keywords: ['ioc','virustotal','abuseipdb'], fields: [{key:'indicators',label:'IPs, domains, hashes',type:'textarea'}]},
  { slug: 'case-manager', name: 'Case Manager', category: 'Forensic Tools', description: 'Create investigation cases, notes, evidence, timeline, and exports.', mode: 'case', icon: Database, keywords: ['case','evidence','forensics'], fields: []},
];

export const suiteToolsBySlug = Object.fromEntries(suiteTools.map(t => [t.slug, t])) as Record<string, SuiteToolDef>;

export const tool = (def: SuiteToolDef) => defineTool({
  name: def.name,
  path: `/${def.slug}`,
  description: def.description,
  keywords: def.keywords,
  component: () => import('./system-tool-suite.vue'),
  icon: def.icon,
  createdAt: new Date(),
});
